### NumPy Arrays
- NumPy array are by default Homogeneous, which means data inside an array must be of the same Datatype. 
- NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.


In [21]:
import numpy as np
print(np.__version__)

2.2.6


In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
type(np.zeros(3))

numpy.ndarray

In [24]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [26]:
np.zeros(3).shape

(3,)

In [27]:
np.zeros((3,2)).shape

(3, 2)

In [28]:
np.zeros(3).ndim

1

In [29]:
np.zeros((3,2)).ndim

2

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.array([[1,2,3,4],[10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [34]:
np.linspace(0,4.5,10)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [35]:
n= 1000000 
a = np.random.rand(n)
b = np.random.rand(n)

In [36]:
import time 
"""
Record multiple running times.
"""
class Timer: 
    def __init__(self):
        self.times = []

    def start(self):
        self.tik = time.time()
    
    def stop(self):
        self.times.append(time.time() - self.tik)
        return self.times[-1]

In [37]:
timer = Timer()

timer.start()
c = np.zeros(n)
for i in range(n):
    c[i] = a[i] + b[i]
timer.stop()

timer.start()
c = a + b
timer.stop()

0.006246328353881836

In [38]:
timer.times

[0.20796775817871094, 0.006246328353881836]

In [39]:
a = np.array([[1,2,3,4],[10,20,30,40]])
print(a)

[[ 1  2  3  4]
 [10 20 30 40]]


In [40]:
b = a.reshape(4,2)
print(b)

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


In [41]:
b[0,1] = -1

In [42]:
print(b)

[[ 1 -1]
 [ 3  4]
 [10 20]
 [30 40]]


In [43]:
print(a)

[[ 1 -1  3  4]
 [10 20 30 40]]


In [44]:
c = np.array([3,4,5,6,7,8,9])

In [45]:
c > 6

array([False, False, False, False,  True,  True,  True])

In [46]:
c[c>6]

array([7, 8, 9])