In [3]:
import numpy as np

In [4]:
x = np.array([3,4])

In [5]:
import math 

def vector_norm(vector):
    squares = [elements**2 for elements in vector]
    return math.sqrt(sum(squares))

In [6]:
vector_norm(x)

5.0

In [7]:
from numpy import linalg 
linalg.norm(x)

np.float64(5.0)

In [8]:
y = np.array([2,3])

In [9]:
np.dot(x,y)

np.int64(18)

In [10]:
np.dot(x,y) == np.dot(y,x)

np.True_

In [11]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [12]:
x = np.array([2,4,5]).reshape(-1,1)
print(x)

[[2]
 [4]
 [5]]


In [13]:
z = np.matmul(A,x)
print(z)

[[25]
 [58]]


In [14]:
A.shape, x.shape, z.shape

((2, 3), (3, 1), (2, 1))

In [15]:
D = np.array([
            [2, 3, 5, 7],
            [11, 13, 17, 19],
            [23, 29, 31, 37]
])

A = np.array([[3], [4], [5]])

In [16]:
try:
    np.matmul(D, A)
except ValueError as e:
    print("ValueError", e)

ValueError matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)


In [17]:
F = np.array([[5,2],
              [4,1],
              [9,3]])
print(F)

[[5 2]
 [4 1]
 [9 3]]


In [18]:
A = np.array([
        [10, 20, 30],
        [40, 50, 60]
])
print(A)

[[10 20 30]
 [40 50 60]]


In [19]:
A.dot(F)

array([[400, 130],
       [940, 310]])

In [20]:
F.dot(A)

array([[130, 200, 270],
       [ 80, 130, 180],
       [210, 330, 450]])

In [21]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [23]:
E = np.array([[1,1.5], [0,1]])
print(E)

[[1.  1.5]
 [0.  1. ]]


In [24]:
E_inv = linalg.inv(E)
print(E_inv)

[[ 1.  -1.5]
 [ 0.   1. ]]


In [25]:
np.matmul(E, E_inv) 

array([[1., 0.],
       [0., 1.]])

In [26]:
np.matmul(E, E_inv)  == np.eye(2)

array([[ True,  True],
       [ True,  True]])

In [27]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

How to extract all numbers between a given range from a numpy array?


In [28]:
# Get all numbers between 8 and 12
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [29]:
index = np.where(np.logical_and(a >= 8, a <=12))
print(index)

(array([3, 4]),)


In [30]:
a[index]

array([ 9, 10])

In [31]:
c = np.array([1,2,3])

In [32]:
mu, med, sd = np.mean(c), np.median(c), np.std(c)
print(mu, med, sd)

2.0 2.0 0.816496580927726


In [33]:
math.sqrt(sum([(item - mu)**2 for item in c])/3)

0.816496580927726

In [34]:
d = (c - mu)/sd
print(d)

[-1.22474487  0.          1.22474487]


In [35]:
print(np.mean(d), np.std(d))

0.0 0.9999999999999999
