# Main libraries:
- torch
- torch.nn
- torch.optim
- torch.utils.data
- torchvision

pip install torch torchvision torchaudio

In [16]:
import torch
print(torch.__version__)

2.9.0+cpu


## Tensors (Core of PyTorch)

- A tensor is like a NumPy array but can run on GPU.

In [17]:
import torch

x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


## Create tensors:

In [18]:
torch.zeros(3,3)
torch.ones(2,2)
torch.rand(3,3)
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

print(a+b)
print(a*b)

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])


## Tensor Attributes

In [20]:
x = torch.rand(3,4)

print(x.shape)
print(x.dtype)
print(x.device)

torch.Size([3, 4])
torch.float32
cpu


# Converting NumPy ↔ PyTorch

In [21]:
import numpy as np

arr = np.array([1,2,3])
tensor = torch.from_numpy(arr)

In [22]:
tensor.numpy()

array([1, 2, 3])

## Autograd

In [23]:
x = torch.tensor(2.0, requires_grad=True)

y = x**2 + 3*x + 1

y.backward()

print(x.grad)

tensor(7.)


## Neural Networks with torch.nn

In [24]:
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(10,5),
    nn.ReLU(),
    nn.Linear(5,1)
)

print(model)

Sequential(
  (0): Linear(in_features=10, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=1, bias=True)
)


## Loss Functions

In [25]:
nn.MSELoss()
nn.CrossEntropyLoss()
nn.BCELoss()

BCELoss()

In [26]:
loss_fn = nn.MSELoss()

pred = torch.tensor([2.5])
target = torch.tensor([3.0])

loss = loss_fn(pred,target)

print(loss)

tensor(0.2500)


## Optimizers

- SGD
- Adam
- RMSprop
- AdamW

In [27]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.001)

# Full Example (Regression)

In [28]:
import torch
import torch.nn as nn
import torch.optim as optim

# Data
X = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y = torch.tensor([[2.0],[4.0],[6.0],[8.0]])

# Model
model = nn.Linear(1,1)

# Loss
loss_fn = nn.MSELoss()

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training
for epoch in range(1000):

    pred = model(X)

    loss = loss_fn(pred,y)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

print("Weight:", model.weight.item())

Weight: 2.0012362003326416


# Custom Neural Network

In [29]:
class Net(nn.Module):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,1)

    def forward(self,x):

        x = torch.relu(self.fc1(x))
        x = self.fc2(x)

        return x

model = Net()

# Dataset & DataLoader

In [30]:
from torch.utils.data import DataLoader, TensorDataset

dataset = TensorDataset(X,y)

loader = DataLoader(dataset, batch_size=2, shuffle=True)

for batch_X, batch_y in loader:
    print(batch_X)

tensor([[2.],
        [3.]])
tensor([[4.],
        [1.]])


## Saving Model


In [31]:
torch.save(model.state_dict(), "model.pth")



## Load model:



In [32]:
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>