# NumPy Arrays
- NumPy array are by default Homogeneous, which means data inside an array must be of the same Datatype. 
- NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

**This  notebook  cover**  

Basic Level 
Topics you included:

- Array creation

   - np.array

   - np.zeros

   - np.ones

   - np.arange

    - np.linspace

- Array attributes

    - shape

   - ndim

    - size

   - dtype

- Indexing & slicing

- Boolean indexing

- Basic operations

- Broadcasting

- Reshape

- Flatten / Ravel

- Stack / Split

- Basic statistics

   - mean

   - median

   - std

   - var

- Sorting & searching

- Universal functions (sqrt, log, sin, etc.)

In [63]:
import numpy as np
print(np.__version__)

2.2.6


## Array Creation



In [64]:
# np.array() - Create from Lists/Tuples

import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)

# 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr3)

# Specify data type
arr_float = np.array([1, 2, 3], dtype=np.float32)
print("Float array:", arr_float)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Float array: [1. 2. 3.]


## np.zeros() - Arrays of Zeros

In [65]:
# 1D zeros
print("1D zeros (5):", np.zeros(5))

# 2D zeros
print("2D zeros (2,3):\n", np.zeros((2, 3)))

# 3D zeros
print("3D zeros (2,2,2):\n", np.zeros((2, 2, 2)))

# Zeros with specific dtype
print("Zeros as int:", np.zeros(3, dtype=int))

1D zeros (5): [0. 0. 0. 0. 0.]
2D zeros (2,3):
 [[0. 0. 0.]
 [0. 0. 0.]]
3D zeros (2,2,2):
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Zeros as int: [0 0 0]


## np.ones() - Arrays of Ones

In [66]:
# 1D ones
print("1D ones (4):", np.ones(4))

# 2D ones
print("2D ones (3,2):\n", np.ones((3, 2)))

# 3D ones
print("3D ones (2,2,3):\n", np.ones((2, 2, 3)))

1D ones (4): [1. 1. 1. 1.]
2D ones (3,2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
3D ones (2,2,3):
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## np.arange() - Range Function

In [67]:
# Basic arange
print("arange(5):", np.arange(5))

# With start and stop
print("arange(2, 8):", np.arange(2, 8))

# With step
print("arange(1, 10, 2):", np.arange(1, 10, 2))

# Float step
print("arange(0, 1, 0.2):", np.arange(0, 1, 0.2))

# Negative step
print("arange(10, 0, -2):", np.arange(10, 0, -2))

arange(5): [0 1 2 3 4]
arange(2, 8): [2 3 4 5 6 7]
arange(1, 10, 2): [1 3 5 7 9]
arange(0, 1, 0.2): [0.  0.2 0.4 0.6 0.8]
arange(10, 0, -2): [10  8  6  4  2]


## np.linspace() - Evenly Spaced Numbers

In [68]:
# Basic linspace
print("linspace(0, 1, 5):", np.linspace(0, 1, 5))

# Exclude endpoint
print("linspace(0, 1, 5, endpoint=False):", 
      np.linspace(0, 1, 5, endpoint=False))

# With retstep (return step size)
values, step = np.linspace(0, 10, 5, retstep=True)
print(f"Values: {values}, Step: {step}")

# 2D linspace
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 4)
X, Y = np.meshgrid(x, y)
print("Meshgrid X:\n", X)
print("Meshgrid Y:\n", Y)

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
linspace(0, 1, 5, endpoint=False): [0.  0.2 0.4 0.6 0.8]
Values: [ 0.   2.5  5.   7.5 10. ], Step: 2.5
Meshgrid X:
 [[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
Meshgrid Y:
 [[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]


#  Array Attributes

## shape - Dimensions of Array

In [69]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.random.rand(2, 3, 4)

print(f"arr1 shape: {arr1.shape}")
print(f"arr2 shape: {arr2.shape}")
print(f"arr3 shape: {arr3.shape}")

# Reshape changes shape
reshaped = arr2.reshape(3, 2)
print(f"Reshaped arr2: {reshaped.shape}")

arr1 shape: (4,)
arr2 shape: (2, 3)
arr3 shape: (2, 3, 4)
Reshaped arr2: (3, 2)


## ndim - Number of Dimensions

In [70]:
print(f"arr1 dimensions: {arr1.ndim}")
print(f"arr2 dimensions: {arr2.ndim}")
print(f"arr3 dimensions: {arr3.ndim}")

# Check dimension of scalar
scalar = np.array(5)
print(f"Scalar dimensions: {scalar.ndim}")

arr1 dimensions: 1
arr2 dimensions: 2
arr3 dimensions: 3
Scalar dimensions: 0


## size - Total Number of Elements

In [71]:
print(f"arr1 size: {arr1.size} elements")
print(f"arr2 size: {arr2.size} elements")
print(f"arr3 size: {arr3.size} elements")

# Verify with multiplication
print(f"arr2 shape {arr2.shape} = {arr2.shape[0] * arr2.shape[1]} elements")

arr1 size: 4 elements
arr2 size: 6 elements
arr3 size: 24 elements
arr2 shape (2, 3) = 6 elements


## dtype - Data Type

In [72]:
# Different data types
int_arr = np.array([1, 2, 3])
float_arr = np.array([1., 2., 3.])
bool_arr = np.array([True, False, True])
complex_arr = np.array([1+2j, 3+4j])

print(f"int_arr dtype: {int_arr.dtype}")
print(f"float_arr dtype: {float_arr.dtype}")
print(f"bool_arr dtype: {bool_arr.dtype}")
print(f"complex_arr dtype: {complex_arr.dtype}")

# Check itemsize (bytes per element)
print(f"int_arr itemsize: {int_arr.itemsize} bytes")
print(f"float_arr itemsize: {float_arr.itemsize} bytes")

int_arr dtype: int64
float_arr dtype: float64
bool_arr dtype: bool
complex_arr dtype: complex128
int_arr itemsize: 8 bytes
float_arr itemsize: 8 bytes


# Indexing & Slicing

## Basic Indexing



In [73]:
# 1D indexing
a = np.arange(10)
print("Array a:", a)
print("First element:", a[0])
print("Last element:", a[-1])
print("Third element:", a[2])

# 2D indexing
b = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\nArray b:\n", b)
print("Element at [1,2]:", b[1, 2])
print("Element at [-1,-1]:", b[-1, -1])
print("First row:", b[0])
print("First column elements:", b[:, 0])

Array a: [0 1 2 3 4 5 6 7 8 9]
First element: 0
Last element: 9
Third element: 2

Array b:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at [1,2]: 60
Element at [-1,-1]: 90
First row: [10 20 30]
First column elements: [10 40 70]


## Slicing

In [74]:
# 1D slicing
a = np.arange(10)
print("a:", a)
print("a[2:7]:", a[2:7])
print("a[:5]:", a[:5])
print("a[5:]:", a[5:])
print("a[1:8:2]:", a[1:8:2])
print("a[::-1]:", a[::-1])  # Reverse

# 2D slicing
b = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
print("\nb:\n", b)
print("First 2 rows, first 2 columns:\n", b[:2, :2])
print("Last 2 rows, last 2 columns:\n", b[-2:, -2:])
print("Every other row, all columns:\n", b[::2, :])
print("Row 0 and 2, columns 1 and 3:\n", b[[0, 2], :][:, [1, 3]])

a: [0 1 2 3 4 5 6 7 8 9]
a[2:7]: [2 3 4 5 6]
a[:5]: [0 1 2 3 4]
a[5:]: [5 6 7 8 9]
a[1:8:2]: [1 3 5 7]
a[::-1]: [9 8 7 6 5 4 3 2 1 0]

b:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First 2 rows, first 2 columns:
 [[1 2]
 [5 6]]
Last 2 rows, last 2 columns:
 [[ 7  8]
 [11 12]]
Every other row, all columns:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Row 0 and 2, columns 1 and 3:
 [[ 2  4]
 [10 12]]


## Boolean Indexing

In [75]:
# Create array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Boolean condition
condition = arr > 5
print("Condition (arr > 5):", condition)
print("Elements > 5:", arr[condition])

# Multiple conditions
condition2 = (arr > 3) & (arr < 8)
print("Elements between 3 and 8:", arr[condition2])

# Using where()
indices = np.where(arr % 2 == 0)
print("Indices of even numbers:", indices)
print("Even numbers:", arr[indices])

# 2D boolean indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = matrix > 5
print("\nMatrix:\n", matrix)
print("Mask (>5):\n", mask)
print("Values >5:", matrix[mask])

# Replace values based on condition
matrix[matrix > 5] = 0
print("Matrix after replacing >5 with 0:\n", matrix)

Condition (arr > 5): [False False False False False  True  True  True  True  True]
Elements > 5: [ 6  7  8  9 10]
Elements between 3 and 8: [4 5 6 7]
Indices of even numbers: (array([1, 3, 5, 7, 9]),)
Even numbers: [ 2  4  6  8 10]

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mask (>5):
 [[False False False]
 [False False  True]
 [ True  True  True]]
Values >5: [6 7 8 9]
Matrix after replacing >5 with 0:
 [[1 2 3]
 [4 5 0]
 [0 0 0]]


# Basic Operations

## Arithmetic Operations

In [76]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a:", a)
print("b:", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a ** 2 =", a ** 2)
print("a % 2 =", a % 2)

# Scalar operations
print("\nScalar operations:")
print("a + 10 =", a + 10)
print("a * 3 =", a * 3)
print("a ** 2 =", a ** 2)

# In-place operations
c = a.copy()
c += 10
print("\nIn-place addition c = a.copy(); c += 10:", c)

a: [1 2 3 4]
b: [5 6 7 8]
a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
a / b = [0.2        0.33333333 0.42857143 0.5       ]
a ** 2 = [ 1  4  9 16]
a % 2 = [1 0 1 0]

Scalar operations:
a + 10 = [11 12 13 14]
a * 3 = [ 3  6  9 12]
a ** 2 = [ 1  4  9 16]

In-place addition c = a.copy(); c += 10: [11 12 13 14]


## Comparison Operations

In [77]:
a = np.array([1, 5, 3, 8, 2])
b = np.array([2, 5, 1, 8, 3])

print("a:", a)
print("b:", b)
print("a > b:", a > b)
print("a >= b:", a >= b)
print("a < b:", a < b)
print("a == b:", a == b)
print("a != b:", a != b)

# Any and all
print("\nAny a > b:", np.any(a > b))
print("All a > b:", np.all(a > b))
print("All a == a:", np.all(a == a))

a: [1 5 3 8 2]
b: [2 5 1 8 3]
a > b: [False False  True False False]
a >= b: [False  True  True  True False]
a < b: [ True False False False  True]
a == b: [False  True False  True False]
a != b: [ True False  True False  True]

Any a > b: True
All a > b: False
All a == a: True


# Broadcasting

## Basic Broadcasting

In [78]:
# Scalar broadcasting
a = np.array([1, 2, 3, 4])
print("a + 10:", a + 10)  # 10 broadcast to all elements

# 1D and scalar
print("\n1D broadcasting:")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_vector = np.array([10, 20, 30])
print("Matrix:\n", matrix)
print("Row vector:", row_vector)
print("Matrix + row_vector:\n", matrix + row_vector)

# Column vector broadcasting
col_vector = np.array([[10], [20], [30]])
print("\nColumn vector:\n", col_vector)
print("Matrix + col_vector:\n", matrix + col_vector)

# Different shapes broadcasting
a = np.array([[1], [2], [3]])  # shape (3,1)
b = np.array([10, 20, 30])     # shape (3,)
print("\na (3x1):\n", a)
print("b (3,):", b)
print("a + b (broadcasted):\n", a + b)  # Results in (3,3)

a + 10: [11 12 13 14]

1D broadcasting:
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row vector: [10 20 30]
Matrix + row_vector:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Column vector:
 [[10]
 [20]
 [30]]
Matrix + col_vector:
 [[11 12 13]
 [24 25 26]
 [37 38 39]]

a (3x1):
 [[1]
 [2]
 [3]]
b (3,): [10 20 30]
a + b (broadcasted):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## Advanced Broadcasting

In [79]:
# Outer product using broadcasting
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
outer = a[:, np.newaxis] * b[np.newaxis, :]
print("Outer product of a and b:\n", outer)

# Adding dimensions
print("\nAdding dimensions with newaxis:")
a = np.array([1, 2, 3])
print("a[:, np.newaxis]:\n", a[:, np.newaxis])  # shape (3,1)
print("a[np.newaxis, :]:\n", a[np.newaxis, :])  # shape (1,3)

# Complex broadcasting
x = np.random.rand(4, 1, 3)
y = np.random.rand(5, 3)
print("\nShapes for broadcasting:")
print(f"x.shape: {x.shape}")
print(f"y.shape: {y.shape}")
result = x + y
print(f"result.shape: {result.shape}")  # (4,5,3)

# Broadcasting rules visualization
print("\nBroadcasting rules:")
print("Mismatching dimensions are padded with 1s from left")
print("Arrays are compatible if dimensions are equal or one is 1")

Outer product of a and b:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Adding dimensions with newaxis:
a[:, np.newaxis]:
 [[1]
 [2]
 [3]]
a[np.newaxis, :]:
 [[1 2 3]]

Shapes for broadcasting:
x.shape: (4, 1, 3)
y.shape: (5, 3)
result.shape: (4, 5, 3)

Broadcasting rules:
Mismatching dimensions are padded with 1s from left
Arrays are compatible if dimensions are equal or one is 1


# Reshape

## reshape() Method

In [80]:
# Basic reshape
a = np.arange(12)
print("Original (12,):", a)

# Reshape to 3x4
b = a.reshape(3, 4)
print("Reshaped to 3x4:\n", b)

# Reshape to 2x6
c = a.reshape(2, 6)
print("Reshaped to 2x6:\n", c)

# Reshape to 2x2x3
d = a.reshape(2, 2, 3)
print("Reshaped to 2x2x3:\n", d)

# Using -1 (auto-calculate dimension)
e = a.reshape(4, -1)  # -1 means infer size
print("Reshaped with -1 (4x?):\n", e)
print(f"Shape: {e.shape}")

# Can't reshape to incompatible size
try:
    a.reshape(5, 3)
except ValueError as e:
    print(f"\nError: {e}")

Original (12,): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Reshaped with -1 (4x?):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)

Error: cannot reshape array of size 12 into shape (5,3)


## resize() vs reshape()

In [81]:
a = np.arange(6)
print("Original a:", a)

# reshape returns new array (may be view or copy)
b = a.reshape(2, 3)
b[0, 0] = 999
print("After modifying reshape result, original a:", a)  # Original may change!

# resize changes array in-place (if size matches)
c = np.arange(6)
c.resize(3, 2)
print("\nAfter c.resize(3,2):\n", c)

# resize can also change total size (unlike reshape)
d = np.arange(4)
d.resize(3, 3)  # Creates 3x3 with repeated values
print("\nAfter d.resize(3,3):\n", d)

Original a: [0 1 2 3 4 5]
After modifying reshape result, original a: [999   1   2   3   4   5]

After c.resize(3,2):
 [[0 1]
 [2 3]
 [4 5]]

After d.resize(3,3):
 [[0 1 2]
 [3 0 0]
 [0 0 0]]


# Flatten / Ravel

## flatten() - Returns Copy

In [82]:
# Create 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)

# Flatten to 1D (returns copy)
flat = arr.flatten()
print("flatten() result:", flat)

# Modify flatten result
flat[0] = 999
print("\nAfter modifying flatten result:")
print("flatten result:", flat)
print("Original array:\n", arr)  # Original unchanged

# Different order options
print("\nflatten order='F' (Fortran style):", arr.flatten(order='F'))
print("flatten order='C' (C style):", arr.flatten(order='C'))

Original array:
 [[1 2 3]
 [4 5 6]]
flatten() result: [1 2 3 4 5 6]

After modifying flatten result:
flatten result: [999   2   3   4   5   6]
Original array:
 [[1 2 3]
 [4 5 6]]

flatten order='F' (Fortran style): [1 4 2 5 3 6]
flatten order='C' (C style): [1 2 3 4 5 6]


## ravel() - Returns View

In [83]:
# Create 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)

# Ravel to 1D (returns view if possible)
rav = arr.ravel()
print("ravel() result:", rav)

# Modify ravel result
rav[0] = 999
print("\nAfter modifying ravel result:")
print("ravel result:", rav)
print("Original array:\n", arr)  # Original changed!

# Different order options
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nravel order='F':", arr2.ravel(order='F'))
print("ravel order='C':", arr2.ravel(order='C'))

# Memory efficiency comparison
print(f"\nflatten() creates copy, ravel() creates view when possible")
print(f"flatten() uses more memory, ravel() is memory efficient")

Original array:
 [[1 2 3]
 [4 5 6]]
ravel() result: [1 2 3 4 5 6]

After modifying ravel result:
ravel result: [999   2   3   4   5   6]
Original array:
 [[999   2   3]
 [  4   5   6]]

ravel order='F': [1 4 2 5 3 6]
ravel order='C': [1 2 3 4 5 6]

flatten() creates copy, ravel() creates view when possible
flatten() uses more memory, ravel() is memory efficient


# Stack / Split

## Stack / Split

In [84]:
# Create arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("a:", a)
print("b:", b)
print("c:", c)

# vstack - vertical stack
v_stack = np.vstack((a, b, c))
print("\nvstack (row-wise):\n", v_stack)

# hstack - horizontal stack
h_stack = np.hstack((a, b, c))
print("\nhstack (column-wise):", h_stack)

# stack with axis parameter
stack_axis0 = np.stack((a, b, c), axis=0)
print("\nstack axis=0:\n", stack_axis0)
stack_axis1 = np.stack((a, b, c), axis=1)
print("stack axis=1:\n", stack_axis1)

# 2D stacking
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print("\nm1:\n", m1)
print("m2:\n", m2)
print("vstack:\n", np.vstack((m1, m2)))
print("hstack:\n", np.hstack((m1, m2)))

a: [1 2 3]
b: [4 5 6]
c: [7 8 9]

vstack (row-wise):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

hstack (column-wise): [1 2 3 4 5 6 7 8 9]

stack axis=0:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
stack axis=1:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

m1:
 [[1 2]
 [3 4]]
m2:
 [[5 6]
 [7 8]]
vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack:
 [[1 2 5 6]
 [3 4 7 8]]


## Splitting Arrays

In [85]:
# Create array
arr = np.arange(12).reshape(4, 3)
print("Original array (4x3):\n", arr)

# hsplit - horizontal split (along columns)
h_split = np.hsplit(arr, 3)  # Split into 3 arrays (each 4x1)
print("\nhsplit into 3:\n")
for i, split_arr in enumerate(h_split):
    print(f"Split {i}:\n{split_arr}")

# vsplit - vertical split (along rows)
v_split = np.vsplit(arr, 2)  # Split into 2 arrays (each 2x3)
print("\nvsplit into 2:\n")
for i, split_arr in enumerate(v_split):
    print(f"Split {i}:\n{split_arr}")

# split with axis
split_axis0 = np.split(arr, 2, axis=0)  # Same as vsplit
split_axis1 = np.split(arr, 3, axis=1)  # Same as hsplit

# Split at specific indices
arr_1d = np.arange(10)
print("\n1D array:", arr_1d)
split_at = np.split(arr_1d, [3, 7])  # Split at indices 3 and 7
print("Split at [3,7]:")
for i, split in enumerate(split_at):
    print(f"Split {i}: {split}")

# array_split - handles uneven splits
arr_uneven = np.arange(10)
uneven_split = np.array_split(arr_uneven, 3)
print("\narray_split into 3 (uneven):")
for i, split in enumerate(uneven_split):
    print(f"Split {i}: {split}")

Original array (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

hsplit into 3:

Split 0:
[[0]
 [3]
 [6]
 [9]]
Split 1:
[[ 1]
 [ 4]
 [ 7]
 [10]]
Split 2:
[[ 2]
 [ 5]
 [ 8]
 [11]]

vsplit into 2:

Split 0:
[[0 1 2]
 [3 4 5]]
Split 1:
[[ 6  7  8]
 [ 9 10 11]]

1D array: [0 1 2 3 4 5 6 7 8 9]
Split at [3,7]:
Split 0: [0 1 2]
Split 1: [3 4 5 6]
Split 2: [7 8 9]

array_split into 3 (uneven):
Split 0: [0 1 2 3]
Split 1: [4 5 6]
Split 2: [7 8 9]


#  Basic Statistics

## mean() - Average

In [86]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print("Array a:", a)
print("Mean of a:", np.mean(a))
print("Mean of a (alternative):", a.mean())

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray b:\n", b)
print("Overall mean:", np.mean(b))
print("Mean along axis=0 (columns):", np.mean(b, axis=0))
print("Mean along axis=1 (rows):", np.mean(b, axis=1))

# With weights
weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
print("\nWeighted mean:", np.average(a, weights=weights))

# Handle NaN
c = np.array([1, 2, np.nan, 4, 5])
print("\nWith NaN:", c)
print("Mean with NaN:", np.nanmean(c))  # Ignores NaN

Array a: [1 2 3 4 5]
Mean of a: 3.0
Mean of a (alternative): 3.0

Array b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Overall mean: 5.0
Mean along axis=0 (columns): [4. 5. 6.]
Mean along axis=1 (rows): [2. 5. 8.]

Weighted mean: 3.2

With NaN: [ 1.  2. nan  4.  5.]
Mean with NaN: 3.0


## median() - Middle Value

In [87]:
# 1D array (odd length)
a = np.array([1, 3, 5, 7, 9])
print("Array a:", a)
print("Median of a:", np.median(a))

# 1D array (even length)
b = np.array([1, 3, 5, 7, 9, 11])
print("\nArray b:", b)
print("Median of b:", np.median(b))  # Average of middle two

# 2D array
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray c:\n", c)
print("Overall median:", np.median(c))
print("Median along axis=0:", np.median(c, axis=0))
print("Median along axis=1:", np.median(c, axis=1))

# With NaN
d = np.array([1, 2, np.nan, 4, 5])
print("\nWith NaN:", d)
print("Median with NaN:", np.nanmedian(d))

Array a: [1 3 5 7 9]
Median of a: 5.0

Array b: [ 1  3  5  7  9 11]
Median of b: 6.0

Array c:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Overall median: 5.0
Median along axis=0: [4. 5. 6.]
Median along axis=1: [2. 5. 8.]

With NaN: [ 1.  2. nan  4.  5.]
Median with NaN: 3.0


## std() - Standard Deviation

In [88]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print("Array a:", a)
print("Std of a:", np.std(a))
print("Std (population):", np.std(a, ddof=0))  # Population std
print("Std (sample):", np.std(a, ddof=1))      # Sample std

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray b:\n", b)
print("Overall std:", np.std(b))
print("Std along axis=0:", np.std(b, axis=0))
print("Std along axis=1:", np.std(b, axis=1))

# Manual calculation verification
mean = np.mean(a)
squared_diff = (a - mean) ** 2
manual_std = np.sqrt(np.mean(squared_diff))
print(f"\nManual std verification: {manual_std:.6f}")
print(f"NumPy std: {np.std(a):.6f}")

# With NaN
c = np.array([1, 2, np.nan, 4, 5])
print("\nWith NaN:", c)
print("Std with NaN:", np.nanstd(c))

Array a: [1 2 3 4 5]
Std of a: 1.4142135623730951
Std (population): 1.4142135623730951
Std (sample): 1.5811388300841898

Array b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Overall std: 2.581988897471611
Std along axis=0: [2.44948974 2.44948974 2.44948974]
Std along axis=1: [0.81649658 0.81649658 0.81649658]

Manual std verification: 1.414214
NumPy std: 1.414214

With NaN: [ 1.  2. nan  4.  5.]
Std with NaN: 1.5811388300841898


## var() - Variance

In [89]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print("Array a:", a)
print("Variance of a:", np.var(a))
print("Variance (population):", np.var(a, ddof=0))
print("Variance (sample):", np.var(a, ddof=1))

# Relationship between std and var
print(f"\nstd^2 = {np.std(a)**2:.6f}")
print(f"var  = {np.var(a):.6f}")

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray b:\n", b)
print("Overall variance:", np.var(b))
print("Variance along axis=0:", np.var(b, axis=0))
print("Variance along axis=1:", np.var(b, axis=1))

# Manual calculation
mean = np.mean(a)
squared_deviations = (a - mean) ** 2
manual_var = np.mean(squared_deviations)
print(f"\nManual variance: {manual_var:.6f}")

Array a: [1 2 3 4 5]
Variance of a: 2.0
Variance (population): 2.0
Variance (sample): 2.5

std^2 = 2.000000
var  = 2.000000

Array b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Overall variance: 6.666666666666667
Variance along axis=0: [6. 6. 6.]
Variance along axis=1: [0.66666667 0.66666667 0.66666667]

Manual variance: 2.000000


## Sorting & Searching

In [90]:
# 1D sorting
a = np.array([3, 1, 4, 1, 5, 9, 2])
print("Original:", a)
print("np.sort():", np.sort(a))
print("In-place sort:")
a.sort()
print(a)

# argsort - returns indices that would sort array
b = np.array([3, 1, 4, 1, 5])
print("\nOriginal b:", b)
indices = np.argsort(b)
print("argsort indices:", indices)
print("Sorted using indices:", b[indices])

# 2D sorting
c = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
print("\nOriginal c:\n", c)
print("Sort along axis=0:\n", np.sort(c, axis=0))
print("Sort along axis=1:\n", np.sort(c, axis=1))

# Descending order
d = np.array([3, 1, 4, 1, 5])
print("\nDescending order:", np.sort(d)[::-1])

# Stable sort with multiple keys
data = np.array([('Alice', 25), ('Bob', 20), ('Charlie', 25)],
                dtype=[('name', 'U10'), ('age', 'i4')])
print("\nStructured array:")
print(data)
print("Sort by age:", np.sort(data, order='age'))

Original: [3 1 4 1 5 9 2]
np.sort(): [1 1 2 3 4 5 9]
In-place sort:
[1 1 2 3 4 5 9]

Original b: [3 1 4 1 5]
argsort indices: [1 3 0 2 4]
Sorted using indices: [1 1 3 4 5]

Original c:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Sort along axis=0:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Sort along axis=1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Descending order: [5 4 3 1 1]

Structured array:
[('Alice', 25) ('Bob', 20) ('Charlie', 25)]
Sort by age: [('Bob', 20) ('Alice', 25) ('Charlie', 25)]


## Searching

In [91]:
# where - find indices where condition is True
a = np.array([1, 2, 3, 2, 1, 2, 3, 2, 1])
print("Array a:", a)
indices = np.where(a == 2)
print("Indices where a == 2:", indices)
print("Values where a == 2:", a[indices])

# where with 3 arguments (condition, x, y)
result = np.where(a > 2, a, 0)
print("Where a > 2 keep a, else 0:", result)

# argmax / argmin - indices of max/min values
b = np.array([3, 1, 4, 1, 5, 9, 2])
print("\nArray b:", b)
print("Index of max value:", np.argmax(b))
print("Max value:", b[np.argmax(b)])
print("Index of min value:", np.argmin(b))
print("Min value:", b[np.argmin(b)])

# 2D argmax/argmin
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray c:\n", c)
print("argmax overall:", np.argmax(c))
print("argmax axis=0:", np.argmax(c, axis=0))
print("argmax axis=1:", np.argmax(c, axis=1))

# nonzero - indices of non-zero elements
d = np.array([0, 2, 0, 3, 0, 4])
print("\nArray d:", d)
print("Non-zero indices:", np.nonzero(d))

# searchsorted - find indices where elements should be inserted
e = np.array([1, 3, 5, 7, 9])
print("\nSorted array e:", e)
print("Where to insert 4:", np.searchsorted(e, 4))
print("Where to insert 6:", np.searchsorted(e, 6))
print("Where to insert [0,4,8]:", np.searchsorted(e, [0, 4, 8]))

# extract - return elements satisfying condition
f = np.array([1, 2, 3, 4, 5, 6])
condition = (f % 2 == 0)
print("\nArray f:", f)
print("Even numbers:", np.extract(condition, f))

Array a: [1 2 3 2 1 2 3 2 1]
Indices where a == 2: (array([1, 3, 5, 7]),)
Values where a == 2: [2 2 2 2]
Where a > 2 keep a, else 0: [0 0 3 0 0 0 3 0 0]

Array b: [3 1 4 1 5 9 2]
Index of max value: 5
Max value: 9
Index of min value: 1
Min value: 1

Array c:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
argmax overall: 8
argmax axis=0: [2 2 2]
argmax axis=1: [2 2 2]

Array d: [0 2 0 3 0 4]
Non-zero indices: (array([1, 3, 5]),)

Sorted array e: [1 3 5 7 9]
Where to insert 4: 2
Where to insert 6: 3
Where to insert [0,4,8]: [0 2 4]

Array f: [1 2 3 4 5 6]
Even numbers: [2 4 6]


# Universal Functions

## Mathematical Functions


In [92]:
# Create sample data
x = np.array([0, np.pi/4, np.pi/2, np.pi])
print("x (radians):", x)

# Trigonometric functions
print("\n=== Trigonometric Functions ===")
print("sin(x):", np.sin(x))
print("cos(x):", np.cos(x))
print("tan(x):", np.tan(x))
print("arcsin(0.5):", np.arcsin(0.5))
print("arccos(0.5):", np.arccos(0.5))
print("arctan(1):", np.arctan(1))

# Degrees/radians conversion
print("\n=== Angle Conversion ===")
print("degrees(π):", np.degrees(np.pi))
print("radians(180°):", np.radians(180))

# Exponential and logarithmic functions
print("\n=== Exponential & Logarithmic ===")
a = np.array([1, 2, 3, 4])
print("a:", a)
print("exp(a):", np.exp(a))
print("exp2(a):", np.exp2(a))  # 2^a
print("log(a):", np.log(a))
print("log10(a):", np.log10(a))
print("log2(a):", np.log2(a))

x (radians): [0.         0.78539816 1.57079633 3.14159265]

=== Trigonometric Functions ===
sin(x): [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(x): [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
tan(x): [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(0.5): 0.5235987755982989
arccos(0.5): 1.0471975511965979
arctan(1): 0.7853981633974483

=== Angle Conversion ===
degrees(π): 180.0
radians(180°): 3.141592653589793

=== Exponential & Logarithmic ===
a: [1 2 3 4]
exp(a): [ 2.71828183  7.3890561  20.08553692 54.59815003]
exp2(a): [ 2.  4.  8. 16.]
log(a): [0.         0.69314718 1.09861229 1.38629436]
log10(a): [0.         0.30103    0.47712125 0.60205999]
log2(a): [0.        1.        1.5849625 2.       ]


## Power and Root Functions

In [93]:
# Power functions
a = np.array([1, 2, 3, 4])
print("a:", a)

# Square
print("square(a):", np.square(a))

# Square root
print("sqrt(a):", np.sqrt(a))

# Power (general)
print("power(a, 3):", np.power(a, 3))
print("power(2, a):", np.power(2, a))

# Cube root
print("cbrt(a):", np.cbrt(a))

# Reciprocal
print("reciprocal(a):", np.reciprocal(a.astype(float)))

# Absolute value
b = np.array([-1, -2, 3, -4])
print("\nb:", b)
print("abs(b):", np.abs(b))
print("fabs(b):", np.fabs(b))  # faster for floats

# Sign
print("sign(b):", np.sign(b))

a: [1 2 3 4]
square(a): [ 1  4  9 16]
sqrt(a): [1.         1.41421356 1.73205081 2.        ]
power(a, 3): [ 1  8 27 64]
power(2, a): [ 2  4  8 16]
cbrt(a): [1.         1.25992105 1.44224957 1.58740105]
reciprocal(a): [1.         0.5        0.33333333 0.25      ]

b: [-1 -2  3 -4]
abs(b): [1 2 3 4]
fabs(b): [1. 2. 3. 4.]
sign(b): [-1 -1  1 -1]


## Rounding Functions

In [94]:
# Rounding examples
x = np.array([3.14159, 2.71828, 1.41421, -2.5, -1.5])
print("Original:", x)

# Round to nearest integer
print("round():", np.round(x))
print("round to 2 decimals:", np.round(x, 2))

# Floor (round down)
print("floor():", np.floor(x))

# Ceil (round up)
print("ceil():", np.ceil(x))

# Truncate (toward zero)
print("trunc():", np.trunc(x))

# Fix (same as trunc)
print("fix():", np.fix(x))

# rint (round to nearest, banker's rounding)
print("rint():", np.rint(x))

Original: [ 3.14159  2.71828  1.41421 -2.5     -1.5    ]
round(): [ 3.  3.  1. -2. -2.]
round to 2 decimals: [ 3.14  2.72  1.41 -2.5  -1.5 ]
floor(): [ 3.  2.  1. -3. -2.]
ceil(): [ 4.  3.  2. -2. -1.]
trunc(): [ 3.  2.  1. -2. -1.]
fix(): [ 3.  2.  1. -2. -1.]
rint(): [ 3.  3.  1. -2. -2.]


## Hyperbolic Functions

In [95]:
x = np.array([0, 1, 2])
print("x:", x)

# Hyperbolic functions
print("\n=== Hyperbolic Functions ===")
print("sinh(x):", np.sinh(x))
print("cosh(x):", np.cosh(x))
print("tanh(x):", np.tanh(x))

# Inverse hyperbolic
print("\n=== Inverse Hyperbolic ===")
print("arcsinh(1):", np.arcsinh(1))
print("arccosh(1):", np.arccosh(1))
print("arctanh(0.5):", np.arctanh(0.5))

x: [0 1 2]

=== Hyperbolic Functions ===
sinh(x): [0.         1.17520119 3.62686041]
cosh(x): [1.         1.54308063 3.76219569]
tanh(x): [0.         0.76159416 0.96402758]

=== Inverse Hyperbolic ===
arcsinh(1): 0.881373587019543
arccosh(1): 0.0
arctanh(0.5): 0.5493061443340549


## Aggregate Functions

In [96]:
# Create array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array a:\n", a)

# Sum
print("\n=== Sum ===")
print("sum():", np.sum(a))
print("sum axis=0:", np.sum(a, axis=0))
print("sum axis=1:", np.sum(a, axis=1))

# Product
print("\n=== Product ===")
print("prod():", np.prod(a))
print("prod axis=0:", np.prod(a, axis=0))
print("prod axis=1:", np.prod(a, axis=1))

# Cumulative sum
print("\n=== Cumulative Sum ===")
print("cumsum():", np.cumsum(a))
print("cumsum axis=0:\n", np.cumsum(a, axis=0))
print("cumsum axis=1:\n", np.cumsum(a, axis=1))

# Cumulative product
print("\n=== Cumulative Product ===")
print("cumprod():", np.cumprod(a.flatten()[:4]))
print("cumprod axis=0:\n", np.cumprod(a, axis=0))

Array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

=== Sum ===
sum(): 45
sum axis=0: [12 15 18]
sum axis=1: [ 6 15 24]

=== Product ===
prod(): 362880
prod axis=0: [ 28  80 162]
prod axis=1: [  6 120 504]

=== Cumulative Sum ===
cumsum(): [ 1  3  6 10 15 21 28 36 45]
cumsum axis=0:
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
cumsum axis=1:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]

=== Cumulative Product ===
cumprod(): [ 1  2  6 24]
cumprod axis=0:
 [[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]


## Comparison Functions

In [97]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 2, 5])

print("a:", a)
print("b:", b)

# Element-wise comparisons
print("\n=== Element-wise ===")
print("greater(a,b):", np.greater(a, b))
print("greater_equal:", np.greater_equal(a, b))
print("less:", np.less(a, b))
print("less_equal:", np.less_equal(a, b))
print("equal:", np.equal(a, b))
print("not_equal:", np.not_equal(a, b))

# Array-wise comparisons
print("\n=== Array-wise ===")
print("array_equal(a,b):", np.array_equal(a, b))
print("array_equiv(a,b):", np.array_equiv(a, b))

# Logical operations
print("\n=== Logical ===")
cond1 = a > 2
cond2 = b < 4
print("a > 2:", cond1)
print("b < 4:", cond2)
print("logical_and:", np.logical_and(cond1, cond2))
print("logical_or:", np.logical_or(cond1, cond2))
print("logical_not:", np.logical_not(cond1))

# All and Any
print("\n=== All/Any ===")
print("all(a > 0):", np.all(a > 0))
print("any(a > 3):", np.any(a > 3))

a: [1 2 3 4]
b: [2 2 2 5]

=== Element-wise ===
greater(a,b): [False False  True False]
greater_equal: [False  True  True False]
less: [ True False False  True]
less_equal: [ True  True False  True]
equal: [False  True False False]
not_equal: [ True False  True  True]

=== Array-wise ===
array_equal(a,b): False
array_equiv(a,b): False

=== Logical ===
a > 2: [False False  True  True]
b < 4: [ True  True  True False]
logical_and: [False False  True False]
logical_or: [ True  True  True  True]
logical_not: [ True  True False False]

=== All/Any ===
all(a > 0): True
any(a > 3): True


## Floating Point Functions

In [98]:
# Create array with special values
a = np.array([0, np.inf, -np.inf, np.nan, 1])
print("Array with special values:", a)

# Check for special values
print("\n=== Special Value Checks ===")
print("isinf:", np.isinf(a))
print("isposinf:", np.isposinf(a))
print("isneginf:", np.isneginf(a))
print("isnan:", np.isnan(a))
print("isfinite:", np.isfinite(a))

# Next after
print("\n=== Next After ===")
print("nextafter(1, 2):", np.nextafter(1, 2))
print("nextafter(1, 0):", np.nextafter(1, 0))

# Spacing
print("\n=== Spacing ===")
print("spacing(1e10):", np.spacing(1e10))
print("spacing(1e-10):", np.spacing(1e-10))

# Floating point limits
print("\n=== Floating Point Limits ===")
print("finfo(float).eps:", np.finfo(float).eps)
print("finfo(float).max:", np.finfo(float).max)
print("finfo(float).min:", np.finfo(float).min)

Array with special values: [  0.  inf -inf  nan   1.]

=== Special Value Checks ===
isinf: [False  True  True False False]
isposinf: [False  True False False False]
isneginf: [False False  True False False]
isnan: [False False False  True False]
isfinite: [ True False False False  True]

=== Next After ===
nextafter(1, 2): 1.0000000000000002
nextafter(1, 0): 0.9999999999999999

=== Spacing ===
spacing(1e10): 1.9073486328125e-06
spacing(1e-10): 1.2924697071141057e-26

=== Floating Point Limits ===
finfo(float).eps: 2.220446049250313e-16
finfo(float).max: 1.7976931348623157e+308
finfo(float).min: -1.7976931348623157e+308
