# Vectorization vs Python Loops

## Performance Comparison

In [42]:
import numpy as np
import time

# Create large arrays
n = 10_000_000
a = np.random.rand(n)
b = np.random.rand(n)

# Python loop method
start = time.time()
c_loop = np.zeros(n)
for i in range(n):
    c_loop[i] = a[i] + b[i]
loop_time = time.time() - start
print(f"Python loop time: {loop_time:.4f} seconds")

# NumPy vectorized method
start = time.time()
c_vec = a + b
vec_time = time.time() - start
print(f"NumPy vectorized time: {vec_time:.4f} seconds")
print(f"Speedup: {loop_time/vec_time:.1f}x")

# More complex operations - loop vs vectorized
def loop_operation(x, y):
    result = np.zeros(len(x))
    for i in range(len(x)):
        result[i] = np.sin(x[i]) * np.cos(y[i]) + np.exp(x[i] * y[i])
    return result

def vec_operation(x, y):
    return np.sin(x) * np.cos(y) + np.exp(x * y)

# Test with smaller array for demonstration
n_small = 1_000_000
x = np.random.rand(n_small)
y = np.random.rand(n_small)

start = time.time()
loop_result = loop_operation(x, y)
loop_time = time.time() - start

start = time.time()
vec_result = vec_operation(x, y)
vec_time = time.time() - start

print(f"\nComplex operation - Loop time: {loop_time:.4f}s")
print(f"Complex operation - Vectorized time: {vec_time:.4f}s")
print(f"Speedup: {loop_time/vec_time:.1f}x")

Python loop time: 2.0544 seconds
NumPy vectorized time: 0.0369 seconds
Speedup: 55.6x

Complex operation - Loop time: 2.2287s
Complex operation - Vectorized time: 0.0221s
Speedup: 100.6x


## Memory Efficiency Comparison

In [43]:
# Memory views vs copies
arr = np.arange(10_000_000)

# Creating a view (no memory copy)
start = time.time()
view = arr[::2]  # Every other element
view_time = time.time() - start
print(f"Creating view time: {view_time:.6f}s")

# Creating a copy
start = time.time()
copy = arr[::2].copy()
copy_time = time.time() - start
print(f"Creating copy time: {copy_time:.6f}s")

# Memory usage
import sys
print(f"\nView memory: {sys.getsizeof(view)} bytes")
print(f"Copy memory: {sys.getsizeof(copy)} bytes")

Creating view time: 0.002504s
Creating copy time: 0.012140s

View memory: 112 bytes
Copy memory: 40000112 bytes


# Dot Product Operations

## Vector Dot Products

In [44]:
# 1D dot products
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print("v1:", v1)
print("v2:", v2)

# Various ways to compute dot product
dot_manual = sum(v1[i] * v2[i] for i in range(len(v1)))
dot_np = np.dot(v1, v2)
dot_vdot = np.vdot(v1, v2)  # For complex conjugates
dot_inner = np.inner(v1, v2)  # Inner product

print(f"\nManual dot product: {dot_manual}")
print(f"np.dot: {dot_np}")
print(f"np.vdot: {dot_vdot}")
print(f"np.inner: {dot_inner}")

# Dot product with complex numbers
c1 = np.array([1+2j, 3+4j])
c2 = np.array([5+6j, 7+8j])
print(f"\nComplex dot product: {np.dot(c1, c2)}")
print(f"Complex vdot (conjugates first): {np.vdot(c1, c2)}")

# Properties of dot product
print(f"\nCommutative? np.dot(v1,v2) == np.dot(v2,v1): {np.dot(v1,v2) == np.dot(v2,v1)}")
print(f"Relationship with norm: np.dot(v1,v1) = {np.dot(v1,v1)}")
print(f"Square of norm: {np.linalg.norm(v1)**2}")

v1: [1 2 3]
v2: [4 5 6]

Manual dot product: 32
np.dot: 32
np.vdot: 32
np.inner: 32

Complex dot product: (-18+68j)
Complex vdot (conjugates first): (70-8j)

Commutative? np.dot(v1,v2) == np.dot(v2,v1): True
Relationship with norm: np.dot(v1,v1) = 14
Square of norm: 14.0


## Matrix-Vector Dot Products

In [45]:
# Matrix @ vector
M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([1, 2, 3])

print("Matrix M (2x3):\n", M)
print("Vector v (3,):", v)

# Different notations
result1 = np.dot(M, v)
result2 = M @ v
result3 = M.dot(v)

print(f"\nM @ v = {result1}")
print(f"All methods give same: {np.all(result1 == result2)}")

# Shape requirements
print(f"\nM shape: {M.shape}, v shape: {v.shape}")
print(f"Result shape: {result1.shape}")

# Multiple vectors at once
V = np.array([[1, 2, 3],
              [4, 5, 6]]).T  # 3x2 matrix
print("\nMultiple vectors V (3x2):\n", V)
results = M @ V
print("M @ V (2x2):\n", results)

Matrix M (2x3):
 [[1 2 3]
 [4 5 6]]
Vector v (3,): [1 2 3]

M @ v = [14 32]
All methods give same: True

M shape: (2, 3), v shape: (3,)
Result shape: (2,)

Multiple vectors V (3x2):
 [[1 4]
 [2 5]
 [3 6]]
M @ V (2x2):
 [[14 32]
 [32 77]]


# Matrix Multiplication

## Basic Matrix Multiplication

In [46]:
# 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Matrix multiplication
C = np.matmul(A, B)
D = A @ B
E = A.dot(B)

print("\nA @ B:\n", C)
print(f"All methods equal: {np.all(C == D) and np.all(C == E)}")

# Manual calculation verification
manual = np.array([[A[0,0]*B[0,0] + A[0,1]*B[1,0], A[0,0]*B[0,1] + A[0,1]*B[1,1]],
                   [A[1,0]*B[0,0] + A[1,1]*B[1,0], A[1,0]*B[0,1] + A[1,1]*B[1,1]]])
print("Manual calculation:\n", manual)

# Matrix multiplication is not commutative
print(f"\nA @ B == B @ A? {np.array_equal(A @ B, B @ A)}")
print("B @ A:\n", B @ A)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

A @ B:
 [[19 22]
 [43 50]]
All methods equal: True
Manual calculation:
 [[19 22]
 [43 50]]

A @ B == B @ A? False
B @ A:
 [[23 34]
 [31 46]]


## Different Shape Multiplications

In [47]:
# Matrix multiplication with different shapes
A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])  # 3x2

print("A (2x3):\n", A)
print("B (3x2):\n", B)
print("A @ B (2x2):\n", A @ B)

# Inner dimensions must match
try:
    C = np.array([[1, 2], [3, 4]])  # 2x2
    result = A @ C  # 2x3 @ 2x2 - invalid
    print(result)
except ValueError as e:
    print(f"\nError (invalid shapes): {e}")

# Batch matrix multiplication
batch_A = np.random.rand(5, 2, 3)  # 5 matrices of shape 2x3
batch_B = np.random.rand(5, 3, 4)  # 5 matrices of shape 3x4
batch_result = np.matmul(batch_A, batch_B)
print(f"\nBatch shapes: {batch_A.shape} @ {batch_B.shape} = {batch_result.shape}")

A (2x3):
 [[1 2 3]
 [4 5 6]]
B (3x2):
 [[ 7  8]
 [ 9 10]
 [11 12]]
A @ B (2x2):
 [[ 58  64]
 [139 154]]

Error (invalid shapes): matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Batch shapes: (5, 2, 3) @ (5, 3, 4) = (5, 2, 4)


# Matrix Transpose

## Basic Transpose Operations

In [48]:
# 2D transpose
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Original A (2x3):\n", A)
print("A.T (3x2):\n", A.T)

# 1D array transpose (does nothing)
v = np.array([1, 2, 3, 4])
print(f"\n1D array v: {v}")
print(f"v.T: {v.T} (same as original)")

# To transpose 1D to column vector
v_col = v[:, np.newaxis]
print(f"v as column:\n{v_col}")
print(f"Shape: {v_col.shape}")

# 3D transpose
B = np.random.rand(2, 3, 4)
print(f"\n3D array B shape: {B.shape}")
print(f"B.T shape: {B.T.shape}")  # Reverses all axes

# Transpose with specific axes
print(f"B transpose with axes (1,0,2): {np.transpose(B, (1,0,2)).shape}")

Original A (2x3):
 [[1 2 3]
 [4 5 6]]
A.T (3x2):
 [[1 4]
 [2 5]
 [3 6]]

1D array v: [1 2 3 4]
v.T: [1 2 3 4] (same as original)
v as column:
[[1]
 [2]
 [3]
 [4]]
Shape: (4, 1)

3D array B shape: (2, 3, 4)
B.T shape: (4, 3, 2)
B transpose with axes (1,0,2): (3, 2, 4)


## Properties of Transpose

In [49]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
B = np.array([[1, 1],
              [0, 1]])

print("A:\n", A)
print("B:\n", B)

# (A^T)^T = A
print(f"\n(A.T).T == A: {np.array_equal((A.T).T, A)}")

# (AB)^T = B^T A^T
AB = A @ B
AB_T = AB.T
B_T_A_T = B.T @ A.T
print(f"\n(AB)^T:\n{AB_T}")
print(f"B^T A^T:\n{B_T_A_T}")
print(f"Equal? {np.array_equal(AB_T, B_T_A_T)}")

# Symmetric matrix check
S = np.array([[1, 2, 3],
              [2, 4, 5],
              [3, 5, 6]])
print(f"\nIs S symmetric? {np.array_equal(S, S.T)}")

A:
 [[1 2]
 [3 4]
 [5 6]]
B:
 [[1 1]
 [0 1]]

(A.T).T == A: True

(AB)^T:
[[ 1  3  5]
 [ 3  7 11]]
B^T A^T:
[[ 1  3  5]
 [ 3  7 11]]
Equal? True

Is S symmetric? True


# Matrix Inverse

## Computing Inverses

In [50]:
from numpy.linalg import inv, LinAlgError

# 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])
print("Matrix A:\n", A)

# Compute inverse
A_inv = inv(A)
print("\nInverse of A:\n", A_inv)

# Verify A @ A_inv = I
I = A @ A_inv
print("\nA @ A_inv:\n", I)
print(f"Is identity? {np.allclose(I, np.eye(2))}")

# Singular matrix (non-invertible)
B = np.array([[1, 2],
              [2, 4]])  # Determinant = 0
try:
    B_inv = inv(B)
    print("B_inv:", B_inv)
except LinAlgError as e:
    print(f"\nError with singular matrix: {e}")

# 3x3 matrix
C = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
C_inv = inv(C)
print("\n3x3 matrix C:\n", C)
print("C inverse:\n", C_inv)
print("C @ C_inv:\n", C @ C_inv)

Matrix A:
 [[4 7]
 [2 6]]

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

A @ A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
Is identity? True

Error with singular matrix: Singular matrix

3x3 matrix C:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
C inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
C @ C_inv:
 [[ 1.00000000e+00 -2.66453526e-15  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.10542736e-15  1.00000000e+00]]


## Properties of Inverse

In [51]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])

print("A:\n", A)
print("B:\n", B)

# (A^{-1})^{-1} = A
A_inv = inv(A)
A_inv_inv = inv(A_inv)
print(f"\n(A^{-1})^{-1} == A: {np.allclose(A, A_inv_inv)}")

# (AB)^{-1} = B^{-1}A^{-1}
AB_inv = inv(A @ B)
B_inv_A_inv = inv(B) @ inv(A)
print(f"\n(AB)^{-1} == B^{-1}A^{-1}: {np.allclose(AB_inv, B_inv_A_inv)}")

# (A^T)^{-1} = (A^{-1})^T
AT_inv = inv(A.T)
A_inv_T = A_inv.T
print(f"\n(A^T)^{-1} == (A^{-1})^T: {np.allclose(AT_inv, A_inv_T)}")

# det(A^{-1}) = 1/det(A)
det_A = np.linalg.det(A)
det_A_inv = np.linalg.det(A_inv)
print(f"\ndet(A) = {det_A:.4f}")
print(f"det(A^{-1}) = {det_A_inv:.4f}")
print(f"1/det(A) = {1/det_A:.4f}")

A:
 [[1 2]
 [3 4]]
B:
 [[2 0]
 [1 2]]

(A^-1)^-1 == A: True

(AB)^-1 == B^-1A^-1: True

(A^T)^-1 == (A^-1)^T: True

det(A) = -2.0000
det(A^-1) = -0.5000
1/det(A) = -0.5000


#  Identity Matrix

## Creating Identity Matrices

In [52]:
# Different ways to create identity
I2 = np.eye(2)
I3 = np.identity(3)
I4 = np.eye(4, dtype=int)

print("2x2 identity:\n", I2)
print("\n3x3 identity:\n", I3)
print("\n4x4 integer identity:\n", I4)

# Non-square "identity-like" matrices
I_rect = np.eye(3, 4)  # 3x4 matrix with ones on diagonal
print("\n3x4 eye matrix:\n", I_rect)

# With offset
I_offset = np.eye(5, k=1)  # Ones on first super-diagonal
print("\nEye with offset k=1:\n", I_offset)

# Property: I @ A = A (for compatible dimensions)
A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3 matrix

# Correct identity matrix for left multiplication (I @ A)
# Should be 2x2 to match A's rows
I_left = np.eye(2)
print(f"\nA shape: {A.shape}")
print(f"Correct I_left shape: {I_left.shape}")
print(f"I_left @ A:\n{I_left @ A}")
print(f"Equal to A? {np.allclose(I_left @ A, A)}")

# For right multiplication (A @ I), identity should match A's columns
I_right = np.eye(3)
print(f"\nA @ I_right (3x3 identity):\n{A @ I_right}")
print(f"Equal to A? {np.allclose(A @ I_right, A)}")

# Alternative: use identity of size matching A's columns for right multiplication
print(f"\nA @ I_3:\n{A @ np.eye(3)}")

2x2 identity:
 [[1. 0.]
 [0. 1.]]

3x3 identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4x4 integer identity:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

3x4 eye matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Eye with offset k=1:
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]

A shape: (2, 3)
Correct I_left shape: (2, 2)
I_left @ A:
[[1. 2. 3.]
 [4. 5. 6.]]
Equal to A? True

A @ I_right (3x3 identity):
[[1. 2. 3.]
 [4. 5. 6.]]
Equal to A? True

A @ I_3:
[[1. 2. 3.]
 [4. 5. 6.]]


# Linear Algebra Basics

## Determinant, Rank, Trace

In [53]:
from numpy.linalg import det, matrix_rank, cond

# Determinant
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(f"det(A) = {det(A):.4f}")
print(f"det(B) = {det(B):.4f}")  # Singular matrix

# Matrix rank
print(f"\nrank(A) = {matrix_rank(A)}")
print(f"rank(B) = {matrix_rank(B)}")  # Rank 2 (not full rank)

# Trace (sum of diagonal)
print(f"\ntrace(A) = {np.trace(A)}")
print(f"trace(B) = {np.trace(B)}")

# Condition number
print(f"\ncond(A) = {cond(A):.4f}")
print(f"cond(eye(3)) = {cond(np.eye(3)):.4f}")

# Norms
v = np.array([3, 4])
print(f"\nVector v: {v}")
print(f"L2 norm: {np.linalg.norm(v)}")
print(f"L1 norm: {np.linalg.norm(v, ord=1)}")
print(f"L∞ norm: {np.linalg.norm(v, ord=np.inf)}")

M = np.array([[1, 2],
              [3, 4]])
print(f"\nMatrix M:\n{M}")
print(f"Frobenius norm: {np.linalg.norm(M, 'fro')}")
print(f"Spectral norm: {np.linalg.norm(M, 2)}")

det(A) = -2.0000
det(B) = 0.0000

rank(A) = 2
rank(B) = 2

trace(A) = 5
trace(B) = 15

cond(A) = 14.9330
cond(eye(3)) = 1.0000

Vector v: [3 4]
L2 norm: 5.0
L1 norm: 7.0
L∞ norm: 4.0

Matrix M:
[[1 2]
 [3 4]]
Frobenius norm: 5.477225575051661
Spectral norm: 5.464985704219043


# Eigenvalues and Eigenvectors

## Basic Eigen Decomposition

In [54]:
from numpy.linalg import eig, eigh

# 2x2 matrix
A = np.array([[3, 1],
              [1, 3]])
print("Matrix A:\n", A)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(A)
print(f"\nEigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

# Verify: A @ v = λv for each eigenvector
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    λ = eigenvalues[i]
    left = A @ v
    right = λ * v
    print(f"\nFor λ = {λ:.4f}:")
    print(f"A@v = {left}")
    print(f"λv = {right}")
    print(f"Equal? {np.allclose(left, right)}")

# 3x3 symmetric matrix (real eigenvalues)
B = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])
print("\nMatrix B:\n", B)

eigvals, eigvecs = eigh(B)  # For symmetric matrices
print(f"\nEigenvalues: {eigvals}")
print(f"Eigenvectors:\n{eigvecs}")

# Properties
print(f"\nSum of eigenvalues = trace: {np.sum(eigvals):.4f} == {np.trace(B)}")
print(f"Product of eigenvalues = det: {np.prod(eigvals):.4f} == {det(B):.4f}")

Matrix A:
 [[3 1]
 [1 3]]

Eigenvalues: [4. 2.]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

For λ = 4.0000:
A@v = [2.82842712 2.82842712]
λv = [2.82842712 2.82842712]
Equal? True

For λ = 2.0000:
A@v = [-1.41421356  1.41421356]
λv = [-1.41421356  1.41421356]
Equal? True

Matrix B:
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

Eigenvalues: [0.58578644 2.         3.41421356]
Eigenvectors:
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01  3.12250226e-16 -7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]

Sum of eigenvalues = trace: 6.0000 == 6
Product of eigenvalues = det: 4.0000 == 4.0000


## Applications of Eigenvalues

In [55]:
# Matrix powers using eigenvalues
A = np.array([[2, 1],
              [1, 2]])
print("Matrix A:\n", A)

# Direct computation of A^5
A_power_5_direct = np.linalg.matrix_power(A, 5)

# Using eigendecomposition: A = V Λ V^{-1}
eigvals, eigvecs = eig(A)
Λ_power_5 = np.diag(eigvals ** 5)
A_power_5_eig = eigvecs @ Λ_power_5 @ inv(eigvecs)

print(f"\nA^5 (direct):\n{A_power_5_direct}")
print(f"A^5 (via eig):\n{A_power_5_eig.real}")
print(f"Equal? {np.allclose(A_power_5_direct, A_power_5_eig.real)}")

# Markov chain example
P = np.array([[0.9, 0.1],
              [0.2, 0.8]])  # Transition matrix
print(f"\nMarkov transition matrix:\n{P}")

# Steady state (eigenvector for eigenvalue 1)
eigvals, eigvecs = eig(P.T)  # Use transpose for left eigenvectors
steady_state = eigvecs[:, np.argmin(np.abs(eigvals - 1))]
steady_state = steady_state / np.sum(steady_state)  # Normalize
print(f"Steady state: {steady_state.real}")

# Verify: P^T @ steady = steady
print(f"P^T @ steady:\n{P.T @ steady_state.real}")

Matrix A:
 [[2 1]
 [1 2]]

A^5 (direct):
[[122 121]
 [121 122]]
A^5 (via eig):
[[122. 121.]
 [121. 122.]]
Equal? True

Markov transition matrix:
[[0.9 0.1]
 [0.2 0.8]]
Steady state: [0.66666667 0.33333333]
P^T @ steady:
[0.66666667 0.33333333]


# Solving Linear Equations

## Basic Systems

In [56]:
from numpy.linalg import solve, lstsq

# 2x2 system
# 2x + y = 5
# x + 3y = 6
A = np.array([[2, 1],
              [1, 3]])
b = np.array([5, 6])

print("System:")
print("2x + y = 5")
print("x + 3y = 6")
print(f"\nA:\n{A}")
print(f"b: {b}")

# Solve using solve (for square matrices)
x = solve(A, b)
print(f"\nSolution: x = {x}")
print(f"Verification: A @ x = {A @ x}")

# 3x3 system
A3 = np.array([[3, 2, -1],
               [2, -2, 4],
               [-1, 0.5, -1]])
b3 = np.array([1, -2, 0])

x3 = solve(A3, b3)
print(f"\n3x3 system solution: {x3}")
print(f"Verification: {np.allclose(A3 @ x3, b3)}")

# Multiple right-hand sides
B = np.array([[5, 10],
              [6, 12]])  # Two RHS vectors
X = solve(A, B)
print(f"\nMultiple RHS solutions:\n{X}")
print(f"Verification:\n{A @ X}")

System:
2x + y = 5
x + 3y = 6

A:
[[2 1]
 [1 3]]
b: [5 6]

Solution: x = [1.8 1.4]
Verification: A @ x = [5. 6.]

3x3 system solution: [ 1. -2. -2.]
Verification: True

Multiple RHS solutions:
[[1.8 3.6]
 [1.4 2.8]]
Verification:
[[ 5. 10.]
 [ 6. 12.]]


## Least Squares Solutions

In [57]:
# Overdetermined system (more equations than unknowns)
# Fitting a line to points
x_points = np.array([0, 1, 2, 3])
y_points = np.array([1, 2.5, 3.5, 4.5])

# We want y = mx + c
# Build A matrix: [x 1] for each point
A = np.vstack([x_points, np.ones(len(x_points))]).T
print("A (design matrix):\n", A)
print("b (targets):", y_points)

# Solve using least squares
solution, residuals, rank, s = lstsq(A, y_points, rcond=None)
m, c = solution
print(f"\nFitted line: y = {m:.4f}x + {c:.4f}")

# Calculate predictions
y_pred = A @ solution
print(f"Predictions: {y_pred}")
print(f"Residuals: {y_points - y_pred}")
print(f"Sum of squared residuals: {np.sum((y_points - y_pred)**2):.4f}")

# Underdetermined system (more unknowns than equations)
A_under = np.array([[1, 2, 3]])
b_under = np.array([6])
x_under = lstsq(A_under, b_under, rcond=None)[0]
print(f"\nUnderdetermined: A @ x = 6")
print(f"One solution: {x_under}")
print(f"Verification: {A_under @ x_under}")

A (design matrix):
 [[0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]]
b (targets): [1.  2.5 3.5 4.5]

Fitted line: y = 1.1500x + 1.1500
Predictions: [1.15 2.3  3.45 4.6 ]
Residuals: [-0.15  0.2   0.05 -0.1 ]
Sum of squared residuals: 0.0750

Underdetermined: A @ x = 6
One solution: [0.42857143 0.85714286 1.28571429]
Verification: [6.]


# Broadcasting Mechanics

## Advanced Broadcasting

In [58]:
# Broadcasting rules in detail
print("Broadcasting Rules:")
print("1. If array shapes differ, prepend 1s to shorter shape")
print("2. Compare dimensions from right to left")
print("3. Dimensions are compatible if equal or one is 1\n")

# Example 1: (3,) + (1,)
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")
print(f"a + b shape: {(a + b).shape}")
print("a + b:\n", a + b)

# Example 2: (4,3) + (3,)
A = np.random.rand(4, 3)
v = np.random.rand(3)
print(f"\nA shape: {A.shape}")
print(f"v shape: {v.shape}")
print(f"A + v shape: {(A + v).shape}")

# Example 3: (4,1) + (3,) -> (4,3)
col = np.array([[1], [2], [3], [4]])
row = np.array([10, 20, 30])
print(f"\ncol shape: {col.shape}")
print(f"row shape: {row.shape}")
print(f"col + row shape: {(col + row).shape}")
print("col + row:\n", col + row)

# Example 4: (2,3,4) + (4,) -> (2,3,4)
cube = np.random.rand(2, 3, 4)
vec = np.random.rand(4)
print(f"\ncube shape: {cube.shape}")
print(f"vec shape: {vec.shape}")
print(f"cube + vec shape: {(cube + vec).shape}")

# Incompatible shapes
try:
    A = np.random.rand(3, 4)
    B = np.random.rand(3, 5)
    C = A + B
except ValueError as e:
    print(f"\nIncompatible shapes error: {e}")

Broadcasting Rules:
1. If array shapes differ, prepend 1s to shorter shape
2. Compare dimensions from right to left
3. Dimensions are compatible if equal or one is 1

a shape: (3,)
b shape: (3, 1)
a + b shape: (3, 3)
a + b:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]

A shape: (4, 3)
v shape: (3,)
A + v shape: (4, 3)

col shape: (4, 1)
row shape: (3,)
col + row shape: (4, 3)
col + row:
 [[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]

cube shape: (2, 3, 4)
vec shape: (4,)
cube + vec shape: (2, 3, 4)

Incompatible shapes error: operands could not be broadcast together with shapes (3,4) (3,5) 


## Practical Broadcasting Examples

In [59]:
# Normalizing data (z-score)
data = np.random.randn(100, 5)  # 100 samples, 5 features
mean = data.mean(axis=0)
std = data.std(axis=0)
normalized = (data - mean) / std
print(f"Original mean: {data.mean(axis=0)[:3]}...")
print(f"Normalized mean: {normalized.mean(axis=0)[:3]}...")

# Outer product using broadcasting
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
outer = x[:, np.newaxis] * y[np.newaxis, :]
print(f"\nOuter product of {x} and {y}:")
print(outer)

# Distance matrix
points = np.array([[0, 0],
                   [1, 1],
                   [2, 2],
                   [3, 3]])
# Compute pairwise distances
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
distances = np.sqrt(np.sum(diff**2, axis=-1))
print(f"\nPairwise distances:\n{distances}")

# Adding bias to multiple layers
X = np.random.randn(10, 3)  # 10 samples, 3 features
W = np.random.randn(3, 5)   # weights
b = np.random.randn(5)      # bias (1D)

# Forward pass: Z = X @ W + b (b broadcast to all samples)
Z = X @ W + b
print(f"\nZ shape: {Z.shape} (b broadcast to all 10 samples)")

Original mean: [ 0.0585653  -0.1436207  -0.01268811]...
Normalized mean: [-3.77475828e-17  4.44089210e-18 -3.88578059e-18]...

Outer product of [1 2 3] and [4 5 6]:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Pairwise distances:
[[0.         1.41421356 2.82842712 4.24264069]
 [1.41421356 0.         1.41421356 2.82842712]
 [2.82842712 1.41421356 0.         1.41421356]
 [4.24264069 2.82842712 1.41421356 0.        ]]

Z shape: (10, 5) (b broadcast to all 10 samples)


# Filtering Values with Conditions

## Basic Filtering

In [60]:
# Simple boolean filtering
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Single condition
filtered = arr[arr > 5]
print("arr > 5:", filtered)

# Multiple conditions
filtered = arr[(arr > 3) & (arr < 8)]
print("3 < arr < 8:", filtered)

# OR condition
filtered = arr[(arr < 3) | (arr > 7)]
print("arr < 3 OR arr > 7:", filtered)

# NOT condition
filtered = arr[~(arr % 2 == 0)]  # Odd numbers
print("Odd numbers:", filtered)

# 2D filtering
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatrix:\n", matrix)

# Filter elements > 5
filtered = matrix[matrix > 5]
print("Elements > 5:", filtered)

# Filter rows where any element > 5
rows = matrix[np.any(matrix > 5, axis=1)]
print("Rows with any element > 5:\n", rows)

# Filter columns where all elements < 8
cols = matrix[:, np.all(matrix < 8, axis=0)]
print("Columns where all < 8:\n", cols)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
arr > 5: [ 6  7  8  9 10]
3 < arr < 8: [4 5 6 7]
arr < 3 OR arr > 7: [ 1  2  8  9 10]
Odd numbers: [1 3 5 7 9]

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elements > 5: [6 7 8 9]
Rows with any element > 5:
 [[4 5 6]
 [7 8 9]]
Columns where all < 8:
 [[1]
 [4]
 [7]]


## Advanced Filtering Techniques

In [61]:
# Filtering with custom functions
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

arr = np.arange(1, 21)
print("Array:", arr)

# Vectorized prime check (using np.vectorize)
is_prime_vec = np.vectorize(is_prime)
primes = arr[is_prime_vec(arr)]
print("Prime numbers:", primes)

# Filtering with np.where for multiple conditions
# Replace even numbers with -1, odd with 1
result = np.where(arr % 2 == 0, -1, 1)
print("Even -> -1, Odd -> 1:", result)

# Complex condition with multiple outcomes
conditions = [
    arr < 5,
    (arr >= 5) & (arr < 10),
    (arr >= 10) & (arr < 15),
    arr >= 15
]
choices = ['Very Low', 'Low', 'Medium', 'High']
categorized = np.select(conditions, choices, default='Unknown')
print("\nCategorized values:")
for val, cat in zip(arr[:5], categorized[:5]):
    print(f"{val} -> {cat}")

# Filtering with NaN handling
data = np.array([1, 2, np.nan, 4, np.nan, 6, 7, np.nan, 9])
print(f"\nData with NaN: {data}")
clean_data = data[~np.isnan(data)]
print(f"Clean data (no NaN): {clean_data}")

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Prime numbers: [ 2  3  5  7 11 13 17 19]
Even -> -1, Odd -> 1: [ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1]

Categorized values:
1 -> Very Low
2 -> Very Low
3 -> Very Low
4 -> Very Low
5 -> Low

Data with NaN: [ 1.  2. nan  4. nan  6.  7. nan  9.]
Clean data (no NaN): [1. 2. 4. 6. 7. 9.]


# np.where - Conditional Selection

## Basic np.where Usage

In [62]:
# 1D where
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)

# Find indices where condition is True
indices = np.where(arr > 3)
print("Indices where arr > 3:", indices)
print("Values where arr > 3:", arr[indices])

# where with 3 arguments (ternary operator)
result = np.where(arr > 3, arr * 10, arr)
print("Where >3 multiply by 10, else keep:", result)

# 2D where
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatrix:\n", matrix)

# Find positions
rows, cols = np.where(matrix > 5)
print(f"Positions where >5: {list(zip(rows, cols))}")
print(f"Values: {matrix[rows, cols]}")

# Replace values based on condition
result = np.where(matrix % 2 == 0, matrix, 0)
print("Even numbers only:\n", result)

Original: [1 2 3 4 5]
Indices where arr > 3: (array([3, 4]),)
Values where arr > 3: [4 5]
Where >3 multiply by 10, else keep: [ 1  2  3 40 50]

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Positions where >5: [(np.int64(1), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(2))]
Values: [6 7 8 9]
Even numbers only:
 [[0 2 0]
 [4 0 6]
 [0 8 0]]


## Advanced np.where Applications

In [63]:
# Multiple conditions with np.where
arr = np.array([-5, -3, -1, 0, 1, 3, 5])

# Categorize numbers
categories = np.where(arr < 0, 'Negative',
             np.where(arr == 0, 'Zero', 'Positive'))
print("Array:", arr)
print("Categories:", categories)

# Handling missing data
data = np.array([1, 2, np.nan, 4, np.nan, 6])
print("\nOriginal data:", data)

# Replace NaN with mean of non-NaN values
mean_val = np.nanmean(data)
clean_data = np.where(np.isnan(data), mean_val, data)
print(f"NaN replaced with {mean_val:.2f}: {clean_data}")

# Clipping values
values = np.array([-10, -5, 0, 5, 10, 15, 20])
clipped = np.where(values < 0, 0,
          np.where(values > 10, 10, values))
print(f"\nOriginal: {values}")
print(f"Clipped (0 to 10): {clipped}")

# Combining arrays based on condition
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
condition = np.array([True, False, True, False])
result = np.where(condition, a, b)
print(f"\nCondition: {condition}")
print(f"a: {a}, b: {b}")
print(f"Result: {result}")

Array: [-5 -3 -1  0  1  3  5]
Categories: ['Negative' 'Negative' 'Negative' 'Zero' 'Positive' 'Positive' 'Positive']

Original data: [ 1.  2. nan  4. nan  6.]
NaN replaced with 3.25: [1.   2.   3.25 4.   3.25 6.  ]

Original: [-10  -5   0   5  10  15  20]
Clipped (0 to 10): [ 0  0  0  5 10 10 10]

Condition: [ True False  True False]
a: [1 2 3 4], b: [10 20 30 40]
Result: [ 1 20  3 40]


# np.vectorize - Vectorizing Functions

## Basic Vectorization

In [64]:
# Custom function that doesn't work with arrays
def f(x):
    if x > 0:
        return x**2
    else:
        return -x

# This won't work with arrays
try:
    result = f(np.array([-2, -1, 0, 1, 2]))
    print(result)
except ValueError as e:
    print(f"Error: {e} - can't use if/else with arrays directly")

# Vectorize the function
f_vec = np.vectorize(f)
result = f_vec(np.array([-2, -1, 0, 1, 2]))
print(f"\nVectorized result: {result}")

# Multiple arguments
def g(x, y):
    return x**2 + y**2

g_vec = np.vectorize(g)
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result = g_vec(x, y)
print(f"\ng({x}, {y}) = {result}")

# With broadcasting
X, Y = np.meshgrid(x, y)
result = g_vec(X, Y)
print("\ng on meshgrid:\n", result)

Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() - can't use if/else with arrays directly

Vectorized result: [2 1 0 1 4]

g([1 2 3], [4 5 6]) = [17 29 45]

g on meshgrid:
 [[17 20 25]
 [26 29 34]
 [37 40 45]]


## Advanced Vectorization Examples

In [65]:
# Complex function with multiple arguments
def temperature_conversion(temp, scale_from, scale_to):
    """Convert between Celsius, Fahrenheit, Kelvin"""
    # First convert to Celsius
    if scale_from == 'F':
        temp_c = (temp - 32) * 5/9
    elif scale_from == 'K':
        temp_c = temp - 273.15
    else:
        temp_c = temp
    
    # Then convert from Celsius to target
    if scale_to == 'F':
        return temp_c * 9/5 + 32
    elif scale_to == 'K':
        return temp_c + 273.15
    else:
        return temp_c

# Vectorize the function
temp_convert_vec = np.vectorize(temperature_conversion)

# Test conversions
temps = np.array([0, 25, 100])
converted = temp_convert_vec(temps, 'C', 'F')
print(f"{temps}°C to Fahrenheit: {converted}°F")

converted = temp_convert_vec(temps, 'C', 'K')
print(f"{temps}°C to Kelvin: {converted}K")

# Multiple conversions at once
temps_c = np.array([-10, 0, 20, 35, 100])
scales_from = np.array(['C', 'C', 'F', 'K', 'C'])
scales_to = np.array(['F', 'K', 'C', 'F', 'K'])

results = temp_convert_vec(temps_c, scales_from, scales_to)
print("\nMixed conversions:")
for t, frm, to, res in zip(temps_c, scales_from, scales_to, results):
    print(f"{t}{frm} -> {to}: {res:.2f}{to}")

# Performance comparison
def slow_function(x):
    result = 0
    for i in range(1000):
        result += np.sin(x) * np.cos(x)
    return result

# Vectorized version
slow_vec = np.vectorize(slow_function)

x = np.random.rand(100)
start = time.time()
slow_result = slow_vec(x)
vec_time = time.time() - start

start = time.time()
direct_result = 1000 * np.sin(x) * np.cos(x)  # Fully vectorized
direct_time = time.time() - start

print(f"\nPerformance: np.vectorize: {vec_time:.4f}s")
print(f"Performance: Fully vectorized: {direct_time:.4f}s")


[  0  25 100]°C to Fahrenheit: [ 32.  77. 212.]°F
[  0  25 100]°C to Kelvin: [273.15 298.15 373.15]K

Mixed conversions:
-10C -> F: 14.00F
0C -> K: 273.15K
20F -> C: -6.67C
35K -> F: -396.67F
100C -> K: 373.15K

Performance: np.vectorize: 0.1279s
Performance: Fully vectorized: 0.0000s


# np.fromfunction - Create Arrays from Functions

## Basic fromfunction Usage

In [66]:
# Simple 2D function
def f(i, j):
    return i + j

arr = np.fromfunction(f, (3, 3), dtype=int)
print("i + j:\n", arr)

# Multiplication table
def mult_table(i, j):
    return (i + 1) * (j + 1)

mult = np.fromfunction(mult_table, (5, 5), dtype=int)
print("\nMultiplication table (5x5):\n", mult)

# Distance from origin
def distance(i, j):
    return np.sqrt(i**2 + j**2)

dist = np.fromfunction(distance, (4, 4))
print("\nDistance from origin:\n", dist.round(2))

# 3D example
def sphere(i, j, k):
    return i**2 + j**2 + k**2 < 10  # Points inside sphere of radius sqrt(10)

sphere_mask = np.fromfunction(sphere, (5, 5, 5), dtype=int)
print(f"\n3D sphere mask shape: {sphere_mask.shape}")
print(f"Number of points inside sphere: {np.sum(sphere_mask)}")

i + j:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]

Multiplication table (5x5):
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]

Distance from origin:
 [[0.   1.   2.   3.  ]
 [1.   1.41 2.24 3.16]
 [2.   2.24 2.83 3.61]
 [3.   3.16 3.61 4.24]]

3D sphere mask shape: (5, 5, 5)
Number of points inside sphere: 29


## Advanced fromfunction Examples

In [67]:
# Creating pattern matrices
def checkerboard(i, j):
    return (i + j) % 2

checker = np.fromfunction(checkerboard, (8, 8), dtype=int)
print("8x8 checkerboard:\n", checker)

# Gradient matrix
def gradient(i, j):
    return i / (j + 1)

grad = np.fromfunction(gradient, (5, 5))
print("\nGradient matrix:\n", grad.round(2))

# Gaussian kernel
def gaussian(i, j, sigma=1.0):
    center = np.array([2, 2])
    r2 = (i - center[0])**2 + (j - center[1])**2
    return np.exp(-r2 / (2 * sigma**2))

gauss = np.fromfunction(gaussian, (5, 5))
print("\nGaussian kernel (5x5):\n", gauss.round(3))

# Custom indices
def custom_func(i, j, k):
    return (2**i) * (3**j) * (5**k)

result = np.fromfunction(custom_func, (3, 3, 3), dtype=int)
print("\n3D array with prime powers shape:", result.shape)
print("Slice at k=0:\n", result[:, :, 0])

8x8 checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

Gradient matrix:
 [[0.   0.   0.   0.   0.  ]
 [1.   0.5  0.33 0.25 0.2 ]
 [2.   1.   0.67 0.5  0.4 ]
 [3.   1.5  1.   0.75 0.6 ]
 [4.   2.   1.33 1.   0.8 ]]

Gaussian kernel (5x5):
 [[0.018 0.082 0.135 0.082 0.018]
 [0.082 0.368 0.607 0.368 0.082]
 [0.135 0.607 1.    0.607 0.135]
 [0.082 0.368 0.607 0.368 0.082]
 [0.018 0.082 0.135 0.082 0.018]]

3D array with prime powers shape: (3, 3, 3)
Slice at k=0:
 [[ 1  3  9]
 [ 2  6 18]
 [ 4 12 36]]


# np.fromiter - Create Arrays from Iterators

## Basic fromiter Usage

In [68]:
# Create from generator
generator = (i**2 for i in range(10))
arr = np.fromiter(generator, dtype=int)
print("Squares from generator:", arr)

# Fibonacci sequence
def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b

fib = np.fromiter(fibonacci(15), dtype=int)
print("\nFirst 15 Fibonacci numbers:", fib)

# From custom iterator
class Counter:
    def __init__(self, start, stop, step):
        self.current = start
        self.stop = stop
        self.step = step
    
    def __iter__(self):
        return self
    
    def __next__(self):
        if self.current >= self.stop:
            raise StopIteration
        value = self.current
        self.current += self.step
        return value

counter = Counter(0, 10, 0.5)
arr = np.fromiter(counter, dtype=float)
print("\nCustom counter:", arr)

# From string iterator
text = "Hello NumPy"
char_codes = np.fromiter(text, dtype='U1')  # Unicode characters
print(f"\nCharacters from '{text}':", char_codes)


Squares from generator: [ 0  1  4  9 16 25 36 49 64 81]

First 15 Fibonacci numbers: [  0   1   1   2   3   5   8  13  21  34  55  89 144 233 377]

Custom counter: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]

Characters from 'Hello NumPy': ['H' 'e' 'l' 'l' 'o' ' ' 'N' 'u' 'm' 'P' 'y']


## Advanced fromiter Examples

In [69]:
# Prime number generator
def prime_generator(n):
    """Generate first n prime numbers"""
    count = 0
    num = 2
    while count < n:
        is_prime = True
        for i in range(2, int(np.sqrt(num)) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            yield num
            count += 1
        num += 1

primes = np.fromiter(prime_generator(20), dtype=int)
print("First 20 primes:", primes)

# Collatz sequence
def collatz(n):
    """Generate Collatz sequence starting from n"""
    while n != 1:
        yield n
        if n % 2 == 0:
            n //= 2
        else:
            n = 3 * n + 1
    yield 1

collatz_seq = np.fromiter(collatz(27), dtype=int)
print(f"\nCollatz sequence starting at 27 (length {len(collatz_seq)}):")
print(collatz_seq)

# Sine wave samples
def sine_wave(freq, duration, sample_rate):
    t = 0
    dt = 1 / sample_rate
    samples = int(duration * sample_rate)
    for _ in range(samples):
        yield np.sin(2 * np.pi * freq * t)
        t += dt

samples = np.fromiter(sine_wave(440, 0.01, 44100), dtype=float)
print(f"\n440Hz sine wave: {len(samples)} samples")
print("First 10 samples:", samples[:10].round(3))

# Running statistics
def running_stats(data):
    """Yield running mean and std"""
    n = 0
    mean = 0
    M2 = 0
    for x in data:
        n += 1
        delta = x - mean
        mean += delta / n
        M2 += delta * (x - mean)
        if n > 1:
            variance = M2 / (n - 1)
            yield mean, np.sqrt(variance)

data = np.random.randn(1000)
stats = np.fromiter(running_stats(data), dtype=[('mean', float), ('std', float)])
print(f"\nRunning statistics shape: {stats.shape}")
print("Final mean:", stats['mean'][-1])
print("Final std:", stats['std'][-1])

First 20 primes: [ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71]

Collatz sequence starting at 27 (length 112):
[  27   82   41  124   62   31   94   47  142   71  214  107  322  161
  484  242  121  364  182   91  274  137  412  206  103  310  155  466
  233  700  350  175  526  263  790  395 1186  593 1780  890  445 1336
  668  334  167  502  251  754  377 1132  566  283  850  425 1276  638
  319  958  479 1438  719 2158 1079 3238 1619 4858 2429 7288 3644 1822
  911 2734 1367 4102 2051 6154 3077 9232 4616 2308 1154  577 1732  866
  433 1300  650  325  976  488  244  122   61  184   92   46   23   70
   35  106   53  160   80   40   20   10    5   16    8    4    2    1]

440Hz sine wave: 441 samples
First 10 samples: [0.    0.063 0.125 0.187 0.248 0.308 0.367 0.425 0.481 0.535]

Running statistics shape: (999,)
Final mean: -0.013935642941094359
Final std: 1.0051891611676154
